name: Continuos Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/AspnetCoreFeatureFlag
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src/AspnetCoreFeatureFlag
